"""AgentCore Runtime entry point for the Strands agent.

This module serves as the handler invoked by AgentCore Runtime.
It loads configuration, builds the agent, and processes invocations
with streaming responses.
"""

import json
import logging
import os
import sys
from typing import Any, Generator

from .config import load_config
from .agent import build_agent

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Module-level agent instance, initialized once at cold start
_agent = None


def _get_agent():
    """Get or initialize the singleton agent instance."""
    global _agent
    if _agent is None:
        config = load_config()
        _agent = build_agent(config)
        logger.info("Agent initialized successfully")
    return _agent


def handle_invocation(event: dict[str, Any]) -> Generator[str, None, None]:
    """Handle an AgentCore Runtime invocation with streaming response.

    Args:
        event: The invocation event containing the prompt and session context.

    Yields:
        Partial text chunks as they are generated by the agent.
    """
    agent = _get_agent()
    prompt = event.get("prompt", "")
    session_id = event.get("session_id", "")

    logger.info("Processing invocation session_id=%s", session_id)

    result = agent(prompt)

    for chunk in result:
        if hasattr(chunk, "text") and chunk.text:
            yield chunk.text
        elif isinstance(chunk, str):
            yield chunk


def handler(event: dict[str, Any], context: Any = None) -> dict[str, Any]:
    """AgentCore Runtime handler entry point.

    Processes the invocation event and returns a streaming response
    compatible with AgentCore Runtime's invocation protocol.

    Args:
        event: The invocation event from AgentCore Runtime.
        context: Runtime context (optional).

    Returns:
        Response dictionary with the agent's output.
    """
    try:
        chunks = []
        for chunk in handle_invocation(event):
            chunks.append(chunk)
        response_text = "".join(chunks)

        return {
            "statusCode": 200,
            "body": response_text,
        }
    except Exception as e:
        logger.exception("Error handling invocation: %s", e)
        return {
            "statusCode": 500,
            "body": json.dumps({"error": str(e)}),
        }


def main() -> None:
    """Local development entry point for running the agent interactively."""
    agent = _get_agent()
    print("Agent ready. Type your prompt (Ctrl+C to exit):")

    while True:
        try:
            prompt = input("\n> ")
            if not prompt.strip():
                continue
            result = agent(prompt)
            for chunk in result:
                if hasattr(chunk, "text") and chunk.text:
                    print(chunk.text, end="", flush=True)
                elif isinstance(chunk, str):
                    print(chunk, end="", flush=True)
            print()
        except KeyboardInterrupt:
            print("\nExiting.")
            break
        except Exception as e:
            print(f"Error: {e}")


if __name__ == "__main__":
    main()
