#!/usr/bin/env python3
"""Capture CloudFormation stack outputs and write to shared/etc/outputs[_<suffix>].sh."""

import json
import os
import subprocess
import sys
from typing import Optional


STACKS = [
    "loom-ecs-cluster",
    "loom-dns",
    "loom-infra",
    "loom-cognito",
    "loom-rds",
    "loom-ec2",
]

# Mapping: (stack, output_key) → env_variable
# All outputs go into a single file; no per-file splitting needed.
OUTPUT_MAP: dict[tuple[str, str], str] = {
    # loom-ecs-cluster
    ("loom-ecs-cluster", "oEcsClusterArn"): "O_ECS_CLUSTER_ARN",
    ("loom-ecs-cluster", "oEcsClusterName"): "O_ECS_CLUSTER_NAME",
    # loom-dns
    ("loom-dns", "oHostedZoneId"): "O_INFRA_HOSTED_ZONE_ID",
    # loom-infra
    ("loom-infra", "oEcsSecurityGroupId"): "O_INFRA_ECS_SG_ID",
    ("loom-infra", "oFrontendTargetGroupArn"): "O_INFRA_FRONTEND_TG_ARN",
    ("loom-infra", "oBackendTargetGroupArn"): "O_INFRA_BACKEND_TG_ARN",
    ("loom-infra", "oFrontendRepositoryUri"): "O_ECR_FRONTEND_URI",
    ("loom-infra", "oBackendRepositoryUri"): "O_ECR_BACKEND_URI",
    # loom-cognito
    ("loom-cognito", "oCognitoUserPoolId"): "O_COGNITO_USER_POOL_ID",
    ("loom-cognito", "oUserClientId"): "O_COGNITO_USER_CLIENT_ID",
    # loom-rds
    ("loom-rds", "oRdsSecretArn"): "O_RDS_SECRET_ARN",
    ("loom-rds", "oConnectEndpoint"): "O_RDS_PROXY_ENDPOINT",
    ("loom-rds", "oRdsPort"): "O_RDS_PORT",
    # loom-ec2
    ("loom-ec2", "oInstanceId"): "O_EC2_INSTANCE_ID",
}


def get_stack_outputs(profile: str, region: str, stack_name: str) -> Optional[dict[str, str]]:
    """Query CloudFormation for stack outputs. Returns None if stack doesn't exist."""
    try:
        result = subprocess.run(
            [
                "aws", "cloudformation", "describe-stacks",
                "--profile", profile,
                "--region", region,
                "--stack-name", stack_name,
                "--query", "Stacks[0].Outputs",
                "--output", "json",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            return None
        outputs = json.loads(result.stdout)
        if not outputs:
            return None
        return {o["OutputKey"]: o["OutputValue"] for o in outputs}
    except (json.JSONDecodeError, subprocess.TimeoutExpired, KeyError):
        return None


def main() -> None:
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <profile> <region> [suffix]")
        print(f"  suffix: account suffix for output file (e.g., 9582 → outputs_9582.sh)")
        print(f"  If omitted, writes to outputs.sh")
        sys.exit(1)

    profile = sys.argv[1]
    region = sys.argv[2]
    suffix = sys.argv[3] if len(sys.argv) > 3 else ""

    # Collect all outputs from all stacks
    all_outputs: dict[str, dict[str, str]] = {}
    ns_delegation: Optional[str] = None

    for stack_name in STACKS:
        print(f"Querying {stack_name}...", end=" ", flush=True)
        outputs = get_stack_outputs(profile, region, stack_name)
        if outputs:
            all_outputs[stack_name] = outputs
            print(f"{len(outputs)} outputs")
            # Capture NS records for display
            if stack_name == "loom-dns" and "oNameServers" in outputs:
                ns_delegation = outputs["oNameServers"]
        else:
            print("not found or no outputs")

    if not all_outputs:
        print("\nNo stack outputs found. Deploy stacks first.")
        sys.exit(1)

    # Build output lines grouped by stack
    lines: list[str] = []
    lines.append("# Stack outputs — single source of truth for all O_* variables")
    lines.append("# Auto-generated by: cd shared && make outputs")
    lines.append("")

    current_stack = None
    for (stack_name, output_key), env_var in OUTPUT_MAP.items():
        if stack_name not in all_outputs:
            if stack_name != current_stack:
                current_stack = stack_name
                lines.append(f"# {stack_name}: not deployed")
            continue
        if output_key not in all_outputs[stack_name]:
            continue

        if stack_name != current_stack:
            current_stack = stack_name
            if lines and lines[-1] != "":
                lines.append("")
            # Collect all output keys for this stack that we found
            found_keys = [
                ok for (sn, ok), _ in OUTPUT_MAP.items()
                if sn == stack_name and ok in all_outputs.get(stack_name, {})
            ]
            lines.append(f"# {stack_name}: {', '.join(found_keys)}")

        value = all_outputs[stack_name][output_key]
        lines.append(f"{env_var}={value}")

    content = "\n".join(lines) + "\n"

    # Print to stdout
    print("\n" + "=" * 72)
    print(content)

    if ns_delegation:
        print("--- Parent account hosted zone (NS delegation) ---")
        print("# Add these NS records to your parent hosted zone:")
        for ns in ns_delegation.split(","):
            print(f"#   {ns.strip()}")
        print()

    # Write to file
    script_dir = os.path.dirname(os.path.abspath(__file__))
    filename = f"outputs_{suffix}.sh" if suffix else "outputs.sh"
    output_file = os.path.join(script_dir, "..", "etc", filename)
    output_file = os.path.normpath(output_file)
    with open(output_file, "w") as f:
        f.write(content)
    print(f"Written to: {output_file}")

    # Also write VITE_COGNITO_USER_CLIENT_ID to frontend/.env if cognito deployed
    if "loom-cognito" in all_outputs and "oUserClientId" in all_outputs["loom-cognito"]:
        client_id = all_outputs["loom-cognito"]["oUserClientId"]
        frontend_env = os.path.normpath(os.path.join(script_dir, "..", "..", "frontend", ".env"))
        with open(frontend_env, "w") as f:
            f.write(f"VITE_COGNITO_USER_CLIENT_ID={client_id}\n")
        print(f"Written to: {frontend_env}")


if __name__ == "__main__":
    main()
